// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zawtwgsnbpvwogamwksa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inphd3R3Z3NuYnB2d29nYW13a3NhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzU3NTc3MTEsImV4cCI6MjA5MTMzMzcxMX0.kAL5z8I9Yb9ZROTFY_14wVKWsoRCg4ktH4VMXAS1J-8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});